services:
  - type: web
    name: myshop2
    env: python
    buildCommand: |
      pip install -r myshop2/myshop/requirements.txt &&
      cd myshop2/myshop &&
      python manage.py makemigrations image_editor &&
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input
    startCommand: cd myshop2/myshop && gunicorn myshop.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: myshop2-db
          property: connectionString

databases:
  - name: myshop2-db
    databaseName: myshop2
    user: myshop2 