databases:
  # PostgreSQL Database
  - name: myshop2-db
    plan: free
    databaseName: myshop2
    user: myshop2_user
    region: oregon

services:
  # Django Web Service
  - type: web
    name: myshop2
    runtime: python
    plan: free
    region: oregon
    rootDir: myshop2/myshop
    buildCommand: git submodule update --init --recursive && pip install -r ../requirements.txt && python manage.py makemigrations image_editor && python manage.py migrate --no-input && python manage.py collectstatic --no-input
    startCommand: gunicorn myshop.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myshop2-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: myshop.settings

